name: Fishing Library PR
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '6.0.x' ]

    steps:
      - uses: actions/checkout@v3
        name: Checkout Code
      
      - uses: actions/setup-dotnet@v2
        name: Install .NET
          with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build Calculator
        run: dotnet build ./src/bobs-fishing.sln --configuration Release --no-restore

      - name: Test Calculator
        run: dotnet test ./src/bobs-fishing.sln --no-restore --verbosity normal
            