name: Fishing Library
on:
  pull_request:
    branches:
      - master
  push: 
    branches: 
      - master
      
env: 
  SLN_PATH: ./src/bobs-fishing.sln
  DOTNET_CURRENT: 6.0.x
  DOTNET_LTS: 3.1.x

jobs:
  build:
    name:  Sanity Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        name: Checkout Code
      
      - uses: actions/setup-dotnet@v2
        name: Install .NET (${{ env.DOTNET_LTS }})
        with:
          dotnet-version: ${{ env.DOTNET_LTS }}

      - uses: actions/setup-dotnet@v2
        name: Install .NET (${{ env.DOTNET_CURRENT }})
        with:
          dotnet-version: ${{ env.DOTNET_CURRENT }}

      - name: Configure Build
        run: ./build/configure-ci-build.ps1
        shell: pwsh
        
      - name: Nuget Restore
        run: dotnet restore ${{ env.SLN_PATH }}

      - name: Build Calculator
        run: dotnet build ${{ env.SLN_PATH }} --configuration Release --no-restore --verbosity normal

      - name: Test Calculator
        run: dotnet test ${{ env.SLN_PATH }} --no-restore